#!/usr/bin/env python3
"""Generate CS231n practice notebooks following the teaching contract."""
import json
import os

def md_cell(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source.splitlines(keepends=True) if isinstance(source, str) else source}

def code_cell(source):
    return {"cell_type": "code", "metadata": {}, "source": source.splitlines(keepends=True) if isinstance(source, str) else source, "outputs": [], "execution_count": None}

def make_notebook(cells):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.0"}
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }

def save_notebook(nb, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(nb, f, ensure_ascii=False, indent=1)

BASE = r"d:\download\6aa68b099b47c2ba093ab510\cs231n-site\notebooks"

# ============================================================
# Lecture 01: Introduction to Computer Vision
# ============================================================
nb01 = make_notebook([
    md_cell("# 计算机视觉导论\n\n> **斯坦福 CS231n Lecture 1** | Deep Learning for Computer Vision\n\n## 本章导读\n\n本节介绍计算机视觉的发展历程、核心任务以及深度学习在其中的关键作用。我们将从历史脉络理解计算机视觉为什么需要深度学习，并通过代码直观感受图像数据的本质。\n\n**学习目标：**\n- 理解计算机视觉的核心任务（分类、检测、分割）\n- 了解 ImageNet 竞赛如何推动深度学习革命\n- 掌握图像的数值表示和基本操作\n\n**参考来源：** [Stanford CS231n](https://cs231n.stanford.edu/)"),
    md_cell("## 1. 直觉理解：什么是计算机视觉？\n\n计算机视觉 (CV) 是让计算机「看懂」图像和视频的学科。人类视觉系统毫不费力地识别物体，但对计算机而言，一张图片只是 $H \\times W \\times 3$ 的数字矩阵。\n\n### 核心任务\n\n| 任务 | 输入 | 输出 | 应用 |\n|------|------|------|------|\n| **图像分类** | 图像 | 类别标签 | 相册分类、医学筛查 |\n| **目标检测** | 图像 | 边界框 + 类别 | 自动驾驶、安防 |\n| **语义分割** | 图像 | 像素级标签 | 医学影像、遥感 |\n| **实例分割** | 图像 | 像素级实例 | 机器人感知 |"),
    md_cell("## 2. 历史脉络：从 ImageNet 到深度学习革命\n\n2012 年，AlexNet 在 ImageNet 竞赛上以 top-5 错误率 15.3% 夺冠，比第二名（传统方法 26.2%）低了近 11 个百分点。这标志着深度学习时代的开启。\n\n[[Krizhevsky et al., 2012]](https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf)\n\n### 计算机视觉发展关键节点\n\n| 年份 | 事件 | 意义 |\n|------|------|------|\n| 2009 | ImageNet 数据集发布 | 大规模标注数据 |\n| 2012 | AlexNet 夺冠 | 深度学习革命 |\n| 2014 | VGG/GoogLeNet | 更深更小的卷积 |\n| 2015 | ResNet | 残差连接，152层 |\n| 2017 | ImageNet 竞赛结束 | top-5 < 2% |\n| 2020 | ViT | Transformer 进入视觉 |\n| 2023 | SAM | 视觉基础模型 |"),
    md_cell("## 3. 手算验证：图像的数值表示\n\n一张 $32 \\times 32$ 的 RGB 图像，其数值表示是什么？\n\n- **形状**：$(32, 32, 3)$，共 $32 \\times 32 \\times 3 = 3072$ 个数值\n- **取值范围**：每个像素每个通道为 0-255 的整数（或 0-1 的浮点数）\n- **存储**：展平后是一个 3072 维向量\n\n### 手算：向量化\n\n对于一张 $2 \\times 2$ 的灰度图，像素值为：\n$$\n\\begin{bmatrix} 10 & 20 \\\\ 30 & 40 \\end{bmatrix}\n$$\n\n展平后：$\\mathbf{x} = [10, 20, 30, 40]^T \\in \\mathbb{R}^4$\n\n对于 RGB 图像，三个通道叠加：$\\mathbf{x} \\in \\mathbb{R}^{H \\times W \\times 3}$"),
    code_cell("# 代码实现：图像的数值表示与可视化\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib\nmatplotlib.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']\nmatplotlib.rcParams['axes.unicode_minus'] = False\nnp.random.seed(42)\n\n# 生成一张 32x32 的模拟 RGB 图像\nimage = np.random.randint(0, 256, (32, 32, 3), dtype=np.uint8)\nprint(f\"图像形状: {image.shape}\")\nprint(f\"数据类型: {image.dtype}\")\nprint(f\"像素值范围: [{image.min()}, {image.max()}]\")\nprint(f\"展平后维度: {image.flatten().shape}\")\nprint(f\"总像素数: {image.shape[0] * image.shape[1]}\")"),
    code_cell("# 可视化图像及其通道\nfig, axes = plt.subplots(1, 4, figsize=(16, 4))\n\naxes[0].imshow(image)\naxes[0].set_title('RGB 图像')\naxes[0].axis('off')\n\nfor i, (ch, name) in enumerate(zip(range(3), ['R 通道', 'G 通道', 'B 通道'])):\n    axes[i+1].imshow(image[:, :, ch], cmap='Reds' if ch == 0 else ('Greens' if ch == 1 else 'Blues'))\n    axes[i+1].set_title(name)\n    axes[i+1].axis('off')\n\nplt.suptitle('图像的通道分解', fontsize=14)\nplt.tight_layout()\nplt.savefig('lecture-01-intro/image_channels.png', dpi=150, bbox_inches='tight')\nplt.show()\nprint(\"图像已保存\")"),
    code_cell("# 模拟 ImageNet 分类任务：简单的距离度量\n# 假设我们有 5 个类别的\"模板\"图像\ntemplates = {\n    '猫': np.random.randint(0, 256, (8, 8, 3), dtype=np.uint8),\n    '狗': np.random.randint(0, 256, (8, 8, 3), dtype=np.uint8),\n    '鸟': np.random.randint(0, 256, (8, 8, 3), dtype=np.uint8),\n    '车': np.random.randint(0, 256, (8, 8, 3), dtype=np.uint8),\n    '船': np.random.randint(0, 256, (8, 8, 3), dtype=np.uint8),\n}\n\n# 生成一张测试图像\ntest_img = np.random.randint(0, 256, (8, 8, 3), dtype=np.uint8)\n\n# 使用 L2 距离进行最近邻分类\ndistances = {}\nfor label, template in templates.items():\n    dist = np.sqrt(np.sum((test_img.astype(float) - template.astype(float)) ** 2))\n    distances[label] = dist\n    print(f\"L2 距离到 '{label}': {dist:.2f}\")\n\npredicted = min(distances, key=distances.get)\nprint(f\"\\n预测类别: {predicted} (距离: {distances[predicted]:.2f})\")\n\n# 可视化距离\nfig, ax = plt.subplots(figsize=(8, 4))\nax.barh(list(distances.keys()), list(distances.values()), color='#ea580c')\nax.set_xlabel('L2 距离')\nax.set_title('测试图像到各模板的距离（越小越相似）')\nplt.tight_layout()\nplt.savefig('lecture-01-intro/distances.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 4. 实验观察：为什么深度学习优于传统方法\n\n从上面的实验可以看到，简单的 L2 距离度量在图像分类上效果很差——因为图像在高维空间中的几何结构非常复杂。深度学习的核心优势在于：\n\n1. **自动特征提取**：CNN 自动学习层次化特征（边缘→纹理→部件→物体）\n2. **端到端优化**：从原始像素到分类标签的统一优化\n3. **数据驱动**：大规模数据集（ImageNet）使得深度模型不再过拟合\n\n### 深度学习的三个要素\n\n| 要素 | 说明 | CS231n 对应 |\n|------|------|-------------|\n| **数据** | ImageNet: 1400万图, 2万类 | L1, L2 |\n| **算力** | GPU 并行计算 | L11 |\n| **算法** | CNN, Transformer, Diffusion | L5-L14 |"),
    md_cell("## 作业\n\n### 作业 1：图像向量化的维度计算\n\n给定一张 $224 \\times 224$ 的 RGB 图像：\n1. 展平后的向量维度是多少？\n2. 如果用 float32 存储，需要多少 MB 内存？\n\n### 作业 2：k-NN 分类器的局限性\n\n思考并回答：为什么 k-NN 在图像分类上效果不好？从**维度灾难**角度分析。\n\n### 作业 3：数据增强的直觉\n\n完成以下代码，实现简单的数据增强（水平翻转）："),
    code_cell("# 作业 3：实现水平翻转数据增强\ndef horizontal_flip(image):\n    \"\"\"水平翻转图像\"\"\"\n    # 在此实现\n    pass\n\n# 测试\ntest_image = np.random.randint(0, 256, (4, 4, 3), dtype=np.uint8)\nflipped = horizontal_flip(test_image)\n\n# 验证\nassert flipped.shape == test_image.shape, \"形状必须一致\"\nassert np.array_equal(flipped[:, ::-1, :], test_image), \"再次翻转应恢复原图\"\nprint(\"作业 3 通过!\")"),
    md_cell("## 参考文献\n\n1. **ImageNet Classification with Deep Convolutional Neural Networks** - Krizhevsky et al., 2012. [NIPS 2012](https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf)\n2. **ImageNet: A Large-Scale Hierarchical Image Database** - Deng et al., 2009. [CVPR 2009](https://image-net.org/papers/imagenet_cvpr09.pdf)\n3. **CS231n Course Notes** - [cs231n.github.io](https://cs231n.github.io/)\n\n---\n\n> 本节内容参考 [Stanford CS231n Lecture 1](https://cs231n.stanford.edu/)"),
])

# ============================================================
# Lecture 02: Image Classification & Linear Classifiers
# ============================================================
nb02 = make_notebook([
    md_cell("# 图像分类与线性分类器\n\n> **斯坦福 CS231n Lecture 2** | Image Classification with Linear Classifiers\n\n## 本章导读\n\n本节介绍图像分类的核心概念：数据驱动方法、k-NN 的局限性、线性分类器（SVM 和 Softmax）。我们将从手算到代码实现，完整理解线性分类器的工作原理。\n\n**学习目标：**\n- 理解图像分类 pipeline\n- 掌握 SVM 和 Softmax 损失函数\n- 从零实现线性分类器\n\n**参考来源：** [CS231n Linear Classification](https://cs231n.github.io/linear-classify/)"),
    md_cell("## 1. 直觉理解：图像分类 pipeline\n\n图像分类的核心流程：\n```\n训练集 → 学习 → 模型参数 (W, b)\n测试图像 → 模型 → 预测标签\n```\n\n### k-NN 的局限\n\nk-NN 虽然直观，但在高维图像空间中存在严重问题：\n- **维度灾难**：高维空间中距离度量失效\n- **计算量**：每个测试样本需要与所有训练样本比较\n- **无参数学习**：训练数据不压缩为模型参数\n\n### Parametric Approach: Linear Classifier\n\n线性分类器是最简单的参数化模型：\n$$f(x_i, W, b) = W x_i + b$$\n\n其中 $x_i \\in \\mathbb{R}^D$（展平的图像），$W \\in \\mathbb{R}^{C \\times D}$（权重矩阵），$b \\in \\mathbb{R}^C$（偏置），$C$ 是类别数。"),
    md_cell("## 2. 手算验证：SVM 损失函数\n\n### Multi-class SVM Loss (Hinge Loss)\n\n对于第 $i$ 个样本，损失为：\n$$L_i = \\sum_{j \\neq y_i} \\max(0, s_j - s_{y_i} + 1)$$\n\n其中 $s_j = W_j x_i + b_j$ 是第 $j$ 类的得分，$y_i$ 是真实标签。\n\n### 手算示例\n\n假设 3 个类别，得分 $s = [2.0, 5.0, 1.0]$，真实标签 $y_i = 0$（第 0 类）。\n\n- $j=1$: $\\max(0, 5.0 - 2.0 + 1) = 4.0$\n- $j=2$: $\\max(0, 1.0 - 2.0 + 1) = 0.0$\n\n总损失 $L_i = 4.0 + 0.0 = 4.0$\n\n### Softmax Loss (Cross-Entropy)\n\n$$L_i = -\\log\\left(\\frac{e^{s_{y_i}}}{\\sum_j e^{s_j}}\\right)$$\n\n对同样的得分：\n- $e^{2.0} \\approx 7.389$, $e^{5.0} \\approx 148.4$, $e^{1.0} \\approx 2.718$\n- 总和 $\\approx 158.5$\n- 概率 $p_0 = 7.389 / 158.5 \\approx 0.0466$\n- 损失 $L_i = -\\log(0.0466) \\approx 3.06$"),
    code_cell("# 代码实现：SVM 和 Softmax 损失函数\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib\nmatplotlib.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']\nmatplotlib.rcParams['axes.unicode_minus'] = False\nnp.random.seed(42)\n\ndef svm_loss(scores, y):\n    \"\"\"多类 SVM 损失 (Hinge Loss)\n    scores: (C,) 得分向量\n    y: int 真实标签\n    \"\"\"\n    margins = np.maximum(0, scores - scores[y] + 1)\n    margins[y] = 0  # 排除正确类别\n    return np.sum(margins)\n\ndef softmax_loss(scores, y):\n    \"\"\"Softmax 损失 (Cross-Entropy)\n    scores: (C,) 得分向量\n    y: int 真实标签\n    \"\"\"\n    shifted = scores - np.max(scores)  # 数值稳定性\n    exp_scores = np.exp(shifted)\n    probs = exp_scores / np.sum(exp_scores)\n    return -np.log(probs[y])\n\n# 验证手算结果\nscores = np.array([2.0, 5.0, 1.0])\ny = 0\nprint(f\"SVM 损失: {svm_loss(scores, y):.2f}  (期望: 4.00)\")\nprint(f\"Softmax 损失: {softmax_loss(scores, y):.4f}  (期望: ~3.06)\")"),
    code_cell("# 完整的线性分类器实现\nclass LinearClassifier:\n    def __init__(self, num_features, num_classes):\n        self.W = np.random.randn(num_classes, num_features) * 0.01\n        self.b = np.zeros(num_classes)\n    \n    def forward(self, X):\n        return X @ self.W.T + self.b\n    \n    def svm_loss_grad(self, X, y, reg=1e-3):\n        N = X.shape[0]\n        scores = self.forward(X)\n        margins = np.maximum(0, scores - scores[np.arange(N), y][:, None] + 1)\n        margins[np.arange(N), y] = 0\n        loss = np.sum(margins) / N + reg * np.sum(self.W ** 2)\n        \n        # 梯度\n        mask = (margins > 0).astype(float)\n        mask[np.arange(N), y] = -np.sum(mask, axis=1)\n        dW = mask.T @ X / N + 2 * reg * self.W\n        db = np.sum(mask, axis=0) / N\n        return loss, dW, db\n    \n    def train(self, X, y, lr=1e-3, reg=1e-3, epochs=100):\n        losses = []\n        for _ in range(epochs):\n            loss, dW, db = self.svm_loss_grad(X, y, reg)\n            self.W -= lr * dW\n            self.b -= lr * db\n            losses.append(loss)\n        return losses\n    \n    def predict(self, X):\n        return np.argmax(self.forward(X), axis=1)\n\n# 生成合成数据\nN, D, C = 200, 4, 3\nX = np.random.randn(N, D)\ny = np.random.randint(0, C, N)\n\n# 训练\nclf = LinearClassifier(D, C)\nlosses = clf.train(X, y, lr=0.1, epochs=100)\nacc = np.mean(clf.predict(X) == y)\nprint(f\"训练准确率: {acc:.2%}\")\n\n# 可视化损失曲线\nfig, ax = plt.subplots(figsize=(8, 4))\nax.plot(losses, color='#ea580c', linewidth=2)\nax.set_xlabel('Epoch')\nax.set_ylabel('SVM Loss')\nax.set_title('线性分类器训练损失曲线')\nplt.tight_layout()\nplt.savefig('lecture-02-classification/training_loss.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 3. 实验观察：SVM vs Softmax\n\n### 损失函数比较\n\n| 特性 | SVM (Hinge) | Softmax (Cross-Entropy) |\n|------|-------------|------------------------|\n| **损失值** | $\\max(0, s_j - s_{y_i} + 1)$ | $-\\log P(y_i)$ |\n| **概率输出** | 无 | 有 |\n| **梯度** | 稀疏（margin=0 时梯度为0） | 稠密 |\n| **对离群点** | 较鲁棒 | 更敏感 |\n\nSVM 的关键特性：一旦正确类别得分比其他类高出 1 以上，该类的损失就为 0，梯度也为 0——模型不再调整。Softmax 则会持续优化，使得概率更接近 1。"),
    code_cell("# SVM vs Softmax 损失函数比较\nscore_gaps = np.linspace(-2, 5, 100)  # s_j - s_{y_i}\nsvm_losses = np.maximum(0, score_gaps + 1)\nsoftmax_losses = -np.log(np.exp(0) / (np.exp(0) + np.exp(score_gaps)))\n\nfig, ax = plt.subplots(figsize=(8, 5))\nax.plot(score_gaps, svm_losses, label='SVM (Hinge)', color='#ea580c', linewidth=2)\nax.plot(score_gaps, softmax_losses, label='Softmax (Cross-Entropy)', color='#2563eb', linewidth=2)\nax.set_xlabel('得分差 $s_j - s_{y_i}$')\nax.set_ylabel('损失')\nax.set_title('SVM vs Softmax 损失函数比较')\nax.legend()\nax.axvline(x=-1, color='gray', linestyle='--', alpha=0.5)\nax.text(-0.9, 3, 'margin=1\\n(SVM 决策边界)', fontsize=10, color='gray')\nplt.tight_layout()\nplt.savefig('lecture-02-classification/svm_vs_softmax.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 作业\n\n### 作业 1：实现 Softmax 损失及其梯度\n\n完成以下 Softmax 分类器的训练代码："),
    code_cell("# 作业 1：实现 Softmax 损失及梯度\ndef softmax_loss_and_grad(W, X, y, reg=1e-3):\n    \"\"\"Softmax 损失和梯度\n    W: (C, D), X: (N, D), y: (N,)\n    返回 loss, dW\n    \"\"\"\n    N = X.shape[0]\n    scores = X @ W.T  # (N, C)\n    # 在此实现 Softmax 损失和梯度\n    pass\n\n# 测试\nW_test = np.random.randn(3, 4) * 0.01\nX_test = np.random.randn(10, 4)\ny_test = np.random.randint(0, 3, 10)\nloss, dW = softmax_loss_and_grad(W_test, X_test, y_test)\nassert loss > 0, \"损失应为正数\"\nassert dW.shape == (3, 4), \"梯度形状应与 W 一致\"\nprint(\"作业 1 通过!\")"),
    md_cell("## 参考文献\n\n1. **CS231n Linear Classification Notes** - [cs231n.github.io/linear-classify](https://cs231n.github.io/linear-classify/)\n2. **CS231n Optimization Notes** - [cs231n.github.io/optimization-1](https://cs231n.github.io/optimization-1/)\n3. **Support Vector Machines** - Cortes & Vapnik, 1995.\n\n---\n\n> 本节内容参考 [Stanford CS231n Lecture 2](https://cs231n.stanford.edu/)"),
])

# ============================================================
# Lecture 03: Regularization & Optimization
# ============================================================
nb03 = make_notebook([
    md_cell("# 正则化与优化\n\n> **斯坦福 CS231n Lecture 3** | Regularization and Optimization\n\n## 本章导读\n\n本节深入讨论如何防止过拟合（正则化）以及如何高效训练模型（优化算法）。我们将从 SGD 到 Adam，逐步理解现代优化器的演进。\n\n**学习目标：**\n- 理解 L2 正则化和 Dropout\n- 掌握 SGD、Momentum、AdaGrad、Adam 的原理\n- 从零实现这些优化器\n\n**参考来源：** [CS231n Optimization](https://cs231n.github.io/optimization-1/) | [Why Momentum Really Works](https://distill.pub/2017/momentum/)"),
    md_cell("## 1. 正则化：防止过拟合\n\n### L2 正则化\n\n在损失函数中加入权重惩罚：\n$$L = \\frac{1}{N} \\sum_i L_i + \\lambda \\|W\\|^2$$\n\nL2 正则化鼓励权重分散到所有特征上，避免过度依赖少数特征。\n\n### Dropout\n\n训练时随机丢弃神经元：\n$$\\tilde{h} = \\frac{h \\cdot \\text{mask}}{p}$$\n\n其中 mask 是以概率 $p$ 生成的 0/1 掩列，$p$ 是保留概率。除以 $p$ 是为了保持期望一致（Inverted Dropout）。"),
    md_cell("## 2. 优化器：从 SGD 到 Adam\n\n### SGD + Momentum\n\n$$v_t = \\gamma v_{t-1} + \\eta \\nabla L(\\theta_t)$$\n$$\\theta_{t+1} = \\theta_t - v_t$$\n\n### AdaGrad\n\n$$G_t = G_{t-1} + g_t^2$$\n$$\\theta_{t+1} = \\theta_t - \\frac{\\eta}{\\sqrt{G_t + \\epsilon}} g_t$$\n\n### Adam\n\n$$m_t = \\beta_1 m_{t-1} + (1-\\beta_1) g_t$$\n$$v_t = \\beta_2 v_{t-1} + (1-\\beta_2) g_t^2$$\n$$\\hat{m}_t = \\frac{m_t}{1-\\beta_1^t}, \\quad \\hat{v}_t = \\frac{v_t}{1-\\beta_2^t}$$\n$$\\theta_{t+1} = \\theta_t - \\eta \\frac{\\hat{m}_t}{\\sqrt{\\hat{v}_t} + \\epsilon}$$"),
    code_cell("# 从零实现四种优化器\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib\nmatplotlib.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']\nmatplotlib.rcParams['axes.unicode_minus'] = False\nnp.random.seed(42)\n\nclass SGD:\n    def __init__(self, params, lr=0.01):\n        self.params, self.lr = params, lr\n    def step(self, grads):\n        for p, g in zip(self.params, grads):\n            p -= self.lr * g\n\nclass Momentum:\n    def __init__(self, params, lr=0.01, momentum=0.9):\n        self.params, self.lr, self.momentum = params, lr, momentum\n        self.v = [np.zeros_like(p) for p in params]\n    def step(self, grads):\n        for i, (p, g) in enumerate(zip(self.params, grads)):\n            self.v[i] = self.momentum * self.v[i] + self.lr * g\n            p -= self.v[i]\n\nclass AdaGrad:\n    def __init__(self, params, lr=0.01, eps=1e-8):\n        self.params, self.lr, self.eps = params, lr, eps\n        self.G = [np.zeros_like(p) for p in params]\n    def step(self, grads):\n        for i, (p, g) in enumerate(zip(self.params, grads)):\n            self.G[i] += g ** 2\n            p -= self.lr * g / (np.sqrt(self.G[i]) + self.eps)\n\nclass Adam:\n    def __init__(self, params, lr=0.001, betas=(0.9, 0.999), eps=1e-8):\n        self.params, self.lr, self.betas, self.eps = params, lr, betas, eps\n        self.m = [np.zeros_like(p) for p in params]\n        self.v = [np.zeros_like(p) for p in params]\n        self.t = 0\n    def step(self, grads):\n        self.t += 1\n        for i, (p, g) in enumerate(zip(self.params, grads)):\n            self.m[i] = self.betas[0] * self.m[i] + (1 - self.betas[0]) * g\n            self.v[i] = self.betas[1] * self.v[i] + (1 - self.betas[1]) * g ** 2\n            m_hat = self.m[i] / (1 - self.betas[0] ** self.t)\n            v_hat = self.v[i] / (1 - self.betas[1] ** self.t)\n            p -= self.lr * m_hat / (np.sqrt(v_hat) + self.eps)\n\nprint(\"四种优化器实现完成\")"),
    code_cell("# 在二次损失函数上比较优化器\n# f(x, y) = 10*x^2 + y^2 (一个方向比另一个陡峭得多)\ndef loss_fn(p):\n    return 10 * p[0]**2 + p[1]**2\n\ndef grad_fn(p):\n    return np.array([20 * p[0], 2 * p[1]])\n\n# 初始点\ninit = np.array([4.0, 3.0])\noptimizers = {\n    'SGD': SGD([init.copy()], lr=0.01),\n    'Momentum': Momentum([init.copy()], lr=0.01),\n    'AdaGrad': AdaGrad([init.copy()], lr=0.1),\n    'Adam': Adam([init.copy()], lr=0.1),\n}\n\ntrajectories = {name: [init.copy()] for name in optimizers}\nfor epoch in range(100):\n    for name, opt in optimizers.items():\n        p = opt.params[0]\n        g = grad_fn(p)\n        opt.step([g])\n        traject_ories[name].append(p.copy())\n\n# 可视化\nfig, ax = plt.subplots(figsize=(8, 6))\ncolors = {'SGD': '#ea580c', 'Momentum': '#2563eb', 'AdaGrad': '#16a34a', 'Adam': '#9333ea'}\nfor name, traj in traject_ories.items():\n    traj = np.array(traj)\n    ax.plot(traj[:, 0], traj[:, 1], label=name, color=colors[name], linewidth=2, marker='.', markersize=2)\n\n# 等高线\nx = np.linspace(-5, 5, 100)\ny = np.linspace(-5, 5, 100)\nX, Y = np.meshgrid(x, y)\nZ = 10 * X**2 + Y**2\nax.contour(X, Y, Z, levels=20, cmap='viridis', alpha=0.3)\nax.set_xlabel('x₁')\nax.set_ylabel('x₂')\nax.set_title('优化器比较：二次损失函数 f = 10x₁² + x₂²')\nax.legend()\nplt.tight_layout()\nplt.savefig('lecture-03-optimization/optimizers_comparison.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 3. 实验观察\n\n从图中可以看到：\n- **SGD** 在陡峭方向（x₁）震荡严重，在平坦方向（x₂）进展缓慢\n- **Momentum** 通过动量累积，在 x₂ 方向加速\n- **AdaGrad** 自适应学习率，在 x₁ 方向自动减小步长\n- **Adam** 结合动量和自适应学习率，收敛最快\n\n[[Kingma & Ba, 2015]](https://arxiv.org/abs/1412.6980) Adam 论文"),
    md_cell("## 作业\n\n### 作业 1：实现 Dropout\n\n完成以下 Dropout 的前向和反向传播："),
    code_cell("# 作业 1：实现 Dropout\ndef dropout_forward(x, p, training=True):\n    \"\"\"Dropout 前向传播\n    x: 输入\n    p: 丢弃概率（0-1）\n    training: 是否训练模式\n    \"\"\"\n    if not training:\n        return x, None\n    mask = None  # 在此实现\n    out = None  # 在此实现\n    return out, (mask, p)\n\ndef dropout_backward(dout, cache):\n    \"\"\"Dropout 反向传播\"\"\"\n    mask, p = cache\n    # 在此实现\n    pass\n\n# 测试\nx = np.random.randn(10, 5)\nout, cache = dropout_forward(x, p=0.3, training=True)\nassert out.shape == x.shape\nprint(\"作业 1 通过!\")"),
    md_cell("## 参考文献\n\n1. **Adam: A Method for Stochastic Optimization** - Kingma & Ba, 2015. [arXiv:1412.6980](https://arxiv.org/abs/1412.6980)\n2. **Why Momentum Really Works** - Distill, 2017. [distill.pub/2017/momentum](https://distill.pub/2017/momentum/)\n3. **Efficient Backprop** - LeCun et al., 1998. [cs231n.stanford.edu/papers/lecun-98b.pdf](https://cs231n.stanford.edu/papers/lecun-98b.pdf)\n4. **Dropout** - Srivastava et al., 2014. [JMLR](https://jmlr.org/papers/v15/srivastava14a.html)\n\n---\n\n> 本节内容参考 [Stanford CS231n Lecture 3](https://cs231n.stanford.edu/)"),
])

# ============================================================
# Lecture 04: Neural Networks & Backpropagation
# ============================================================
nb04 = make_notebook([
    md_cell("# 神经网络与反向传播\n\n> **斯坦福 CS231n Lecture 4** | Neural Networks and Backpropagation\n\n## 本章导读\n\n本节介绍多层感知机（MLP）和反向传播算法——深度学习的基石。我们将从计算图出发，手算反向传播，然后从零实现一个两层神经网络。\n\n**学习目标：**\n- 理解计算图和反向传播原理\n- 掌握链式法则在神经网络中的应用\n- 从零实现 MLP 并训练\n\n**参考来源：** [CS231n Backpropagation](https://cs231n.github.io/optimization-2/) | [Efficient Backprop](https://cs231n.stanford.edu/papers/lecun-98b.pdf)"),
    md_cell("## 1. 计算图与反向传播\n\n### 计算图\n\n将数学表达式拆解为基本运算的图：\n```\nf(x, y) = (x + y) * (y - z)\n```\n分解为：\n- $a = x + y$\n- $b = y - z$\n- $f = a \\times b$\n\n### 链式法则\n\n$$\\frac{\\partial f}{\\partial x} = \\frac{\\partial f}{\\partial a} \\cdot \\frac{\\partial a}{\\partial x}$$\n\n反向传播就是沿计算图反向传播梯度。"),
    md_cell("## 2. 手算验证\n\n### 示例：$f(x, y, z) = (x + y) \\cdot (y - z)$\n\n设 $x=2, y=3, z=1$：\n- $a = x + y = 5$\n- $b = y - z = 2$\n- $f = a \\times b = 10$\n\n反向传播：\n- $\\frac{\\partial f}{\\partial a} = b = 2$\n- $\\frac{\\partial f}{\\partial b} = a = 5$\n- $\\frac{\\partial a}{\\partial x} = 1 \\Rightarrow \\frac{\\partial f}{\\partial x} = 2 \\times 1 = 2$\n- $\\frac{\\partial a}{\\partial y} = 1 \\Rightarrow \\frac{\\partial f}{\\partial y} = 2 \\times 1 + 5 \\times 1 = 7$\n- $\\frac{\\partial b}{\\partial z} = -1 \\Rightarrow \\frac{\\partial f}{\\partial z} = 5 \\times (-1) = -5$"),
    code_cell("# 代码实现：计算图节点\nclass Node:\n    def __init__(self, value=None, grad=None):\n        self.value = value\n        self.grad = grad\n        self._backward = None\n    \n    def forward(self):\n        pass\n    \n    def backward(self):\n        pass\n\n# 手动构建计算图验证\nx, y, z = 2, 3, 1\na = x + y  # 5\nb = y - z  # 2\nf = a * b  # 10\nprint(f\"f = {f}\")\n\n# 反向传播\ndfda = b  # 2\ndfdb = a  # 5\ndfdx = dfda * 1  # 2\ndfdy = dfda * 1 + dfdb * 1  # 7\ndfdz = dfdb * (-1)  # -5\nprint(f\"df/dx = {dfdx}\")\nprint(f\"df/dy = {dfdy}\")\nprint(f\"df/dz = {dfdz}\")"),
    code_cell("# 从零实现两层神经网络\nclass TwoLayerNet:\n    def __init__(self, input_dim, hidden_dim, num_classes, reg=1e-3):\n        self.params = {\n            'W1': np.random.randn(input_dim, hidden_dim) * np.sqrt(2.0 / input_dim),\n            'b1': np.zeros(hidden_dim),\n            'W2': np.random.randn(hidden_dim, num_classes) * np.sqrt(2.0 / hidden_dim),\n            'b2': np.zeros(num_classes),\n        }\n        self.reg = reg\n    \n    def forward(self, X):\n        W1, b1 = self.params['W1'], self.params['b1']\n        W2, b2 = self.params['W2'], self.params['b2']\n        z1 = X @ W1 + b1\n        a1 = np.maximum(0, z1)  # ReLU\n        scores = a1 @ W2 + b2\n        cache = (X, W1, b1, z1, a1, W2, b2)\n        return scores, cache\n    \n    def loss(self, X, y):\n        scores, cache = self.forward(X)\n        N = X.shape[0]\n        shifted = scores - np.max(scores, axis=1, keepdims=True)\n        exp_scores = np.exp(shifted)\n        probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)\n        correct_logprobs = -np.log(probs[np.arange(N), y])\n        data_loss = np.sum(correct_logprobs) / N\n        reg_loss = 0.5 * self.reg * (np.sum(self.params['W1']**2) + np.sum(self.params['W2']**2))\n        loss = data_loss + reg_loss\n        \n        # 反向传播\n        X, W1, b1, z1, a1, W2, b2 = cache\n        dscores = probs.copy()\n        dscores[np.arange(N), y] -= 1\n        dscores /= N\n        dW2 = a1.T @ dscores + self.reg * W2\n        db2 = np.sum(dscores, axis=0)\n        da1 = dscores @ W2.T\n        dz1 = da1 * (z1 > 0)  # ReLU 梯度\n        dW1 = X.T @ dz1 + self.reg * W1\n        db1 = np.sum(dz1, axis=0)\n        grads = {'W1': dW1, 'b1': db1, 'W2': dW2, 'b2': db2}\n        return loss, grads\n    \n    def train(self, X, y, lr=1e-2, epochs=200):\n        losses = []\n        for _ in range(epochs):\n            loss, grads = self.loss(X, y)\n            for k in self.params:\n                self.params[k] -= lr * grads[k]\n            losses.append(loss)\n        return losses\n\n# 测试\nnp.random.seed(42)\nN, D, H, C = 200, 10, 20, 3\nX = np.random.randn(N, D)\ny = np.random.randint(0, C, N)\nnet = TwoLayerNet(D, H, C)\nlosses = net.train(X, y, lr=0.1, epochs=300)\nscores, _ = net.forward(X)\npred = np.argmax(scores, axis=1)\nacc = np.mean(pred == y)\nprint(f\"训练准确率: {acc:.2%}\")\n\nfig, ax = plt.subplots(figsize=(8, 4))\nax.plot(losses, color='#ea580c', linewidth=2)\nax.set_xlabel('Epoch')\nax.set_ylabel('Loss')\nax.set_title('两层神经网络训练损失')\nplt.tight_layout()\nplt.savefig('lecture-04-backprop/training_loss.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 3. 实验观察：ReLU vs Sigmoid\n\n### 激活函数对比\n\n| 激活函数 | 公式 | 梯度 | 优点 | 缺点 |\n|---------|------|------|------|------|\n| **Sigmoid** | $\\frac{1}{1+e^{-x}}$ | $\\sigma(1-\\sigma)$ | 平滑、有界 | 梯度消失、非零中心 |\n| **ReLU** | $\\max(0, x)$ | $x>0 ? 1 : 0$ | 计算快、不饱和 | 神经元死亡 |\n| **Leaky ReLU** | $\\max(0.01x, x)$ | $x>0 ? 1 : 0.01$ | 不死亡 | 需调参 |\n\nReLU 的核心优势在于其在正区间的梯度恒为 1，有效缓解了深度网络的梯度消失问题。"),
    code_cell("# 激活函数可视化\nx = np.linspace(-6, 6, 200)\nsigmoid = 1 / (1 + np.exp(-x))\nrelu = np.maximum(0, x)\nleaky_relu = np.where(x > 0, x, 0.01 * x)\n\nfig, axes = plt.subplots(1, 3, figsize=(15, 4))\nfor ax, fn, name, color in zip(axes, [sigmoid, relu, leaky_relu], \n    ['Sigmoid', 'ReLU', 'Leaky ReLU'], ['#2563eb', '#ea580c', '#16a34a']):\n    ax.plot(x, fn, color=color, linewidth=2)\n    ax.axhline(y=0, color='gray', linewidth=0.5)\n    ax.axvline(x=0, color='gray', linewidth=0.5)\n    ax.set_title(name)\n    ax.set_ylim(-1, 6)\nplt.suptitle('激活函数比较', fontsize=14)\nplt.tight_layout()\nplt.savefig('lecture-04-backprop/activation_functions.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 作业\n\n### 作业 1：实现 Leaky ReLU 的前向和反向传播"),
    code_cell("# 作业 1：实现 Leaky ReLU\ndef leaky_relu_forward(x, slope=0.01):\n    \"\"\"Leaky ReLU 前向传播\"\"\"\n    pass\n\ndef leaky_relu_backward(dout, x, slope=0.01):\n    \"\"\"Leaky ReLU 反向传播\"\"\"\n    pass\n\nx_test = np.array([-2, -1, 0, 1, 2])\nout = leaky_relu_forward(x_test)\nassert np.allclose(out, [-0.02, -0.01, 0, 1, 2])\nprint(\"作业 1 通过!\")"),
    md_cell("## 参考文献\n\n1. **CS231n Backpropagation Notes** - [cs231n.github.io/optimization-2](https://cs231n.github.io/optimization-2/)\n2. **Efficient Backprop** - LeCun et al., 1998. [PDF](https://cs231n.stanford.edu/papers/lecun-98b.pdf)\n3. **Derivatives Notes** - [cs231n.stanford.edu/handouts/derivatives.pdf](https://cs231n.stanford.edu/handouts/derivatives.pdf)\n4. **Deep Learning Book** - Goodfellow et al., 2016. [Chapter 6](http://www.deeplearningbook.org/contents/mlp.html)\n\n---\n\n> 本节内容参考 [Stanford CS231n Lecture 4](https://cs231n.stanford.edu/)"),
])

# ============================================================
# Lecture 05: Convolutional Neural Networks
# ============================================================
nb05 = make_notebook([
    md_cell("# 卷积神经网络\n\n> **斯坦福 CS231n Lecture 5** | Image Classification with CNNs\n\n## 本章导读\n\n卷积神经网络 (CNN) 是计算机视觉的核心架构。本节从卷积运算的直觉出发，手算验证，然后从零实现卷积层和池化层，最后可视化 CNN 学习的特征图。\n\n**学习目标：**\n- 理解卷积运算的数学原理\n- 掌握参数共享和局部连接的优势\n- 从零实现 Conv2d 和 MaxPool2d\n- 可视化 CNN 特征图\n\n**参考来源：** [CS231n CNN Notes](https://cs231n.github.io/convolutional-networks/)"),
    md_cell("## 1. 卷积运算\n\n### 卷积层的核心概念\n\n- **局部连接**：每个神经元只看局部区域（感受野）\n- **参数共享**：同一滤波器在整张图上滑动\n- **平移等变性**：特征检测不依赖位置\n\n### 数学定义\n\n对于输入 $X \\in \\mathbb{R}^{C_{in} \\times H \\times W}$，卷积核 $K \\in \\mathbb{R}^{C_{out} \\times C_{in} \\times K_H \\times K_W}$：\n\n$$\\text{out}[c_{out}, i, j] = \\sum_{c_{in}} \\sum_{di} \\sum_{dj} X[c_{in}, i+di, j+dj] \\cdot K[c_{out}, c_{in}, di, dj]$$\n\n### 输出尺寸计算\n$$H_{out} = \\frac{H_{in} + 2P - K_H}{S} + 1$$\n\n其中 $P$ 是 padding，$S$ 是 stride。"),
    md_cell("## 2. 手算验证\n\n### 示例：单通道 3×3 输入，2×2 卷积核，无 padding，stride=1\n\n输入：\n$$\nX = \\begin{bmatrix} 1 & 2 & 0 \\\\ 0 & 1 & 1 \\\\ 3 & 0 & 2 \\end{bmatrix}\n$$\n\n卷积核：\n$$\nK = \\begin{bmatrix} 1 & 0 \\\\ 0 & 1 \\end{bmatrix}\n$$\n\n输出（2×2）：\n- $\\text{out}[0,0] = 1 \\times 1 + 2 \\times 0 + 0 \\times 0 + 1 \\times 1 = 2$\n- $\\text{out}[0,1] = 2 \\times 1 + 0 \\times 0 + 1 \\times 0 + 1 \\times 1 = 3$\n- $\\text{out}[1,0] = 0 \\times 1 + 1 \\times 0 + 3 \\times 0 + 0 \\times 1 = 0$\n- $\\text{out}[1,1] = 1 \\times 1 + 1 \\times 0 + 0 \\times 0 + 2 \\times 1 = 3$\n\n$$\\text{out} = \\begin{bmatrix} 2 & 3 \\\\ 0 & 3 \\end{bmatrix}$$"),
    code_cell("# 从零实现卷积层（朴素版本）\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib\nmatplotlib.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']\nmatplotlib.rcParams['axes.unicode_minus'] = False\nnp.random.seed(42)\n\ndef conv2d_naive(x, kernel, stride=1, padding=0):\n    \"\"\"朴素卷积实现\n    x: (C_in, H, W)\n    kernel: (C_out, C_in, KH, KW)\n    \"\"\"\n    C_in, H, W = x.shape\n    C_out, _, KH, KW = kernel.shape\n    \n    if padding > 0:\n        x = np.pad(x, ((0,0), (padding, padding), (padding, padding)), mode='constant')\n        H, W = H + 2*padding, W + 2*padding\n    \n    H_out = (H - KH) // stride + 1\n    W_out = (W - KW) // stride + 1\n    out = np.zeros((C_out, H_out, W_out))\n    \n    for co in range(C_out):\n        for i in range(H_out):\n            for j in range(W_out):\n                h_start = i * stride\n                w_start = j * stride\n                receptive = x[:, h_start:h_start+KH, w_start:w_start+KW]\n                out[co, i, j] = np.sum(receptive * kernel[co])\n    return out\n\n# 验证手算结果\nX = np.array([[[1, 2, 0], [0, 1, 1], [3, 0, 2]]], dtype=float)\nK = np.array([[[[1, 0], [0, 1]]]], dtype=float)\nout = conv2d_naive(X, K, stride=1, padding=0)\nprint(f\"卷积输出:\\n{out[0]}\")\nprint(f\"期望输出: [[2, 3], [0, 3]]\")\nassert np.allclose(out[0], [[2, 3], [0, 3]]), \"与手算结果不一致!\"\nprint(\"验证通过!\")"),
    code_cell("# 从零实现 MaxPool 层\ndef maxpool2d_naive(x, pool_size=2, stride=2):\n    \"\"\"朴素最大池化\n    x: (C, H, W)\n    \"\"\"\n    C, H, W = x.shape\n    H_out = (H - pool_size) // stride + 1\n    W_out = (W - pool_size) // stride + 1\n    out = np.zeros((C, H_out, W_out))\n    \n    for c in range(C):\n        for i in range(H_out):\n            for j in range(W_out):\n                h_start = i * stride\n                w_start = j * stride\n                out[c, i, j] = np.max(x[c, h_start:h_start+pool_size, w_start:w_start+pool_size])\n    return out\n\n# 测试池化\nx_test = np.array([[[1, 2, 3, 4],\n                     [5, 6, 7, 8],\n                     [9, 10, 11, 12],\n                     [13, 14, 15, 16]]], dtype=float)\npooled = maxpool2d_naive(x_test)\nprint(f\"池化输出:\\n{pooled[0]}\")\nassert pooled[0, 0, 0] == 6, \"左上角应为6\"\nassert pooled[0, 0, 1] == 8, \"右上角应为8\"\nprint(\"池化验证通过!\")"),
    code_cell("# 可视化卷积特征图\n# 使用常见滤波器\nfrom scipy import ndimage\n\n# 生成一个模拟图像\nimage = np.zeros((16, 16))\nimage[4:12, 4:12] = 1  # 中心方块\nimage += np.random.randn(16, 16) * 0.1\n\n# 定义滤波器\nfilters = {\n    '水平边缘': np.array([[-1, -1, -1], [0, 0, 0], [1, 1, 1]]),\n    '垂直边缘': np.array([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]]),\n    '对角线': np.array([[0, 1, 1], [-1, 0, 1], [-1, -1, 0]]),\n    '模糊': np.ones((3, 3)) / 9,\n    '锐化': np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]]),\n}\n\nfig, axes = plt.subplots(1, len(filters) + 1, figsize=(18, 4))\naxes[0].imshow(image, cmap='gray')\naxes[0].set_title('原始图像')\naxes[0].axis('off')\n\nfor i, (name, kernel) in enumerate(filters.items()):\n    result = ndimage.convolve(image, kernel)\n    axes[i+1].imshow(result, cmap='viridis')\n    axes[i+1].set_title(name)\n    axes[i+1].axis('off')\n\nplt.suptitle('卷积滤波器特征图可视化', fontsize=14)\nplt.tight_layout()\nplt.savefig('lecture-05-cnn/feature_maps.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 3. 实验观察：CNN 的层次化特征\n\nCNN 的核心优势在于自动学习层次化特征：\n- **浅层**：边缘、颜色、纹理\n- **中层**：部件、模式（眼睛、车轮）\n- **深层**：物体、场景\n\n这种层次化表示是通过反向传播自动学习的，不需要人工设计特征。\n\n### 参数量比较\n\n| 层类型 | 参数量 | 感受野 |\n|-------|--------|--------|\n| 全连接 (1000→1000) | 1,000,000 | 全局 |\n| 卷积 (3×3, 64通道) | 576 + 64 | 局部 |\n| 参数比 | ~1700:1 | 局部→全局 |\n\n参数共享使得 CNN 在图像任务上远比 MLP 高效。"),
    md_cell("## 作业\n\n### 作业 1：计算输出尺寸\n\n给定输入 $32 \\times 32 \\times 3$，卷积核 $5 \\times 5 \\times 3 \\times 10$，stride=2，padding=2，输出尺寸是多少？"),
    code_cell("# 作业 1：验证输出尺寸\ndef conv_output_size(H_in, W_in, K, S, P):\n    \"\"\"计算卷积输出尺寸\"\"\"\n    H_out = None  # 在此实现\n    W_out = None\n    return H_out, W_out\n\nH, W = conv_output_size(32, 32, 5, 2, 2)\nassert H == 16 and W == 16, f\"期望 (16, 16), 得到 ({H}, {W})\"\nprint(\"作业 1 通过!\")"),
    md_cell("## 参考文献\n\n1. **CS231n Convolutional Networks Notes** - [cs231n.github.io/convolutional-networks](https://cs231n.github.io/convolutional-networks/)\n2. **Deep Learning Book Ch. 9** - Goodfellow et al., 2016. [Chapter 9](http://www.deeplearningbook.org/contents/convnets.html)\n3. **Understanding CNNs** - Zeiler & Fergus, 2014. [ECCV 2014](https://arxiv.org/abs/1411.2524)\n\n---\n\n> 本节内容参考 [Stanford CS231n Lecture 5](https://cs231n.stanford.edu/)"),
])

# ============================================================
# Lecture 06: CNN Architectures
# ============================================================
nb06 = make_notebook([
    md_cell("# CNN 经典架构\n\n> **斯坦福 CS231n Lecture 6** | CNN Architectures\n\n## 本章导读\n\n从 AlexNet 到 ResNet，本节梳理经典 CNN 架构的演进脉络，理解每个架构的创新点和设计思想。我们将从零实现关键组件并可视化架构差异。\n\n**学习目标：**\n- 理解 AlexNet、VGG、GoogLeNet、ResNet 的架构创新\n- 掌握 Batch Normalization 原理\n- 理解残差连接为何能训练极深网络\n- 从零实现 BatchNorm 和 Residual Block\n\n**参考来源：** [CS231n CNN Architectures](https://cs231n.github.io/convolutional-networks/)"),
    md_cell("## 1. 架构演进概览\n\n| 年份 | 架构 | 层数 | Top-5 错误率 | 核心创新 |\n|------|------|------|-------------|----------|\n| 2012 | AlexNet | 8 | 15.3% | ReLU, Dropout, GPU |\n| 2014 | VGG | 16-19 | 7.3% | 小卷积核堆叠 |\n| 2014 | GoogLeNet | 22 | 6.7% | Inception 模块 |\n| 2015 | ResNet | 152 | 3.6% | 残差连接 |\n\n[[He et al., 2015]](https://arxiv.org/abs/1512.03385) ResNet 论文\n\n### 关键趋势\n1. **更深**：8层 → 152层\n2. **更小的卷积核**：11×11 → 3×3\n3. **更少的参数**：GoogLeNet 仅 6M 参数\n4. **更好的训练技术**：BN, 残差连接"),
    md_cell("## 2. 残差连接（ResNet 的核心）\n\n### 问题：为什么深层网络更难训练？\n\n理论上更深的网络应该至少不比浅层网络差（可以学恒等映射），但实际上梯度消失/爆炸使得深层网络难以训练。\n\n### 解决方案：残差连接\n\n$$\\mathbf{y} = F(\\mathbf{x}, W_i) + \\mathbf{x}$$\n\n网络学习残差 $F(\\mathbf{x})$ 而非直接学习 $H(\\mathbf{x})$。如果最优映射是恒等映射，只需 $F \\to 0$。\n\n### 手算验证\n\n假设 $\\mathbf{x} = [1, 2]$，经过一层后 $F(\\mathbf{x}) = [0.1, -0.1]$。\n- **无残差**：$\\mathbf{y} = F(\\mathbf{x}) = [0.1, -0.1]$\n- **有残差**：$\\mathbf{y} = F(\\mathbf{x}) + \\mathbf{x} = [1.1, 1.9]$\n\n残差连接使得梯度可以跳过非线性层直接传播。"),
    code_cell("# 从零实现 Batch Normalization\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib\nmatplotlib.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']\nmatplotlib.rcParams['axes.unicode_minus'] = False\nnp.random.seed(42)\n\ndef batchnorm_forward(x, gamma, beta, eps=1e-5):\n    \"\"\"BatchNorm 前向传播\n    x: (N, D)\n    gamma, beta: (D,)\n    \"\"\"\n    mean = np.mean(x, axis=0)\n    var = np.var(x, axis=0)\n    x_norm = (x - mean) / np.sqrt(var + eps)\n    out = gamma * x_norm + beta\n    cache = (x, x_norm, mean, var, gamma, beta, eps)\n    return out, cache\n\ndef batchnorm_backward(dout, cache):\n    \"\"\"BatchNorm 反向传播\"\"\"\n    x, x_norm, mean, var, gamma, beta, eps = cache\n    N = x.shape[0]\n    dgamma = np.sum(dout * x_norm, axis=0)\n    dbeta = np.sum(dout, axis=0)\n    dx_norm = dout * gamma\n    dvar = np.sum(dx_norm * (x - mean) * -0.5 * (var + eps)**(-1.5), axis=0)\n    dmean = np.sum(dx_norm * -1 / np.sqrt(var + eps), axis=0) + dvar * np.mean(-2 * (x - mean), axis=0)\n    dx = dx_norm / np.sqrt(var + eps) + dvar * 2 * (x - mean) / N + dmean / N\n    return dx, dgamma, dbeta\n\n# 测试 BN\nx = np.random.randn(100, 5) * 3 + 2\ngamma = np.ones(5)\nbeta = np.zeros(5)\nout, cache = batchnorm_forward(x, gamma, beta)\nprint(f\"输入均值: {x.mean(axis=0)[:3]}\")\nprint(f\"输入标准差: {x.std(axis=0)[:3]}\")\nprint(f\"输出均值: {out.mean(axis=0)[:3]}\")\nprint(f\"输出标准差: {out.std(axis=0)[:3]}\")"),
    code_cell("# 从零实现残差块\ndef residual_block_forward(x, W1, b1, W2, b2, gamma=None, beta=None):\n    \"\"\"残差块前向传播\n    x -> Linear -> ReLU -> Linear -> BN -> + x -> ReLU -> out\n    \"\"\"\n    identity = x\n    z1 = x @ W1 + b1\n    a1 = np.maximum(0, z1)\n    z2 = a1 @ W2 + b2\n    if gamma is not None:\n        z2, _ = batchnorm_forward(z2, gamma, beta)\n    out = np.maximum(0, z2 + identity)\n    return out\n\n# 可视化残差连接的效果\n# 模拟梯度流\ndepths = [10, 20, 50, 100, 152, 200]\nwithout_res = []\nwith_res = []\nfor d in depths:\n    # 无残差：梯度 ~ (0.9)^d（近似）\n    without_res.append(0.9 ** d)\n    # 有残差：梯度 ~ max(0.9^d, 1.0)（至少有直连路径）\n    with_res.append(max(0.9 ** d, 0.5))\n\nfig, ax = plt.subplots(figsize=(8, 5))\nax.semilogy(depths, without_res, 'o-', label='无残差连接', color='#dc2626', linewidth=2)\nax.semilogy(depths, with_res, 's-', label='有残差连接', color='#16a34a', linewidth=2)\nax.set_xlabel('网络深度')\nax.set_ylabel('梯度强度')\nax.set_title('残差连接对梯度传播的影响')\nax.legend()\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.savefig('lecture-06-architectures/residual_gradient.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 3. 架构对比可视化\n\n### 各架构参数量与深度\n\n| 架构 | 深度 | 参数量 | 特点 |\n|------|------|--------|------|\n| AlexNet | 8 | 60M | 大卷积核, 两GPU |\n| VGG-16 | 16 | 138M | 3×3卷积堆叠 |\n| GoogLeNet | 22 | 6M | Inception, 1×1卷积 |\n| ResNet-50 | 50 | 25M | 瓶颈块, BN |\n| ResNet-152 | 152 | 60M | 极深残差 |\n\nVGG 用大量 3×3 卷积堆叠替代大卷积核——两个 3×3 的感受野等于一个 5×5，但参数更少且非线性更强。"),
    code_cell("# 可视化架构参数量和深度\narchitectures = ['AlexNet', 'VGG-16', 'GoogLeNet', 'ResNet-50', 'ResNet-152']\nparams = [60, 138, 6, 25, 60]  # 百万\ndepths = [8, 16, 22, 50, 152]\nerrors = [15.3, 7.3, 6.7, 3.6, 3.6]  # top-5 错误率\n\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))\n\ncolors = ['#ea580c', '#2563eb', '#16a34a', '#9333ea', '#dc2626']\nax1.bar(architectures, params, color=colors)\nax1.set_ylabel('参数量 (百万)')\nax1.set_title('各架构参数量对比')\nax1.tick_params(axis='x', rotation=15)\n\nax2.plot(depths, errors, 'o-', color='#ea580c', linewidth=2, markersize=8)\nfor d, e, a in zip(depths, errors, architectures):\n    ax2.annotate(a, (d, e), textcoords=\"offset points\", xytext=(5, 5), fontsize=9)\nax2.set_xlabel('网络深度（层数）')\nax2.set_ylabel('Top-5 错误率 (%)')\nax2.set_title('深度 vs 准确率')\nax2.invert_yaxis()\nax2.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.savefig('lecture-06-architectures/architecture_comparison.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 作业\n\n### 作业 1：实现瓶颈残差块\n\nResNet-50 使用瓶颈块（Bottleneck）：1×1 → 3×3 → 1×1，减少计算量。"),
    code_cell("# 作业 1：计算瓶颈块参数量\n# 瓶颈块: 1x1(64) -> 3x3(64) -> 1x1(256)\n# 标准块: 3x3(64) -> 3x3(64)\n\ndef count_params(kernel_h, kernel_w, in_ch, out_ch):\n    return kernel_h * kernel_w * in_ch * out_ch + out_ch\n\nbottleneck = count_params(1,1,256,64) + count_params(3,3,64,64) + count_params(1,1,64,256)\nstandard = count_params(3,3,256,64) + count_params(3,3,64,64)\n\nprint(f\"瓶颈块参数量: {bottleneck:,}\")\nprint(f\"标准块参数量: {standard:,}\")\nassert bottleneck < standard, \"瓶颈块参数量应更少\"\nprint(f\"参数减少: {(1 - bottleneck/standard)*100:.1f}%\")\nprint(\"作业 1 通过!\")"),
    md_cell("## 参考文献\n\n1. **ImageNet Classification with Deep CNNs** - Krizhevsky et al., 2012. [NIPS 2012](https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks.pdf)\n2. **Very Deep Convolutional Networks (VGG)** - Simonyan & Zisserman, 2014. [arXiv:1409.1556](https://arxiv.org/abs/1409.1556)\n3. **Going Deeper with Convolutions (GoogLeNet)** - Szegedy et al., 2014. [arXiv:1409.4842](https://arxiv.org/abs/1409.4842)\n4. **Deep Residual Learning (ResNet)** - He et al., 2015. [arXiv:1512.03385](https://arxiv.org/abs/1512.03385)\n5. **Batch Normalization** - Ioffe & Szegedy, 2015. [arXiv:1502.03167](https://arxiv.org/abs/1502.03167)\n\n---\n\n> 本节内容参考 [Stanford CS231n Lecture 6](https://cs231n.stanford.edu/)"),
])

# ============================================================
# Lecture 08: Attention & Transformers
# ============================================================
nb08 = make_notebook([
    md_cell("# 注意力机制与 Transformer\n\n> **斯坦福 CS231n Lecture 8** | Attention and Transformers\n\n## 本章导读\n\nTransformer 架构已超越 CNN 成为视觉领域的主流模型。本节从自注意力机制出发，手算 QKV 计算，然后从零实现 Multi-Head Attention，最后理解 ViT 如何将 Transformer 应用于图像。\n\n**学习目标：**\n- 理解 Self-Attention 的 QKV 模型\n- 从零实现 Multi-Head Attention\n- 理解 ViT 的 Patch Embedding\n\n**参考来源：** [Attention is All You Need](https://arxiv.org/abs/1706.03762) | [ViT](https://arxiv.org/abs/2010.11929)"),
    md_cell("## 1. Self-Attention 机制\n\n### 核心公式\n\n$$\\text{Attention}(Q, K, V) = \\text{softmax}\\left(\\frac{Q K^T}{\\sqrt{d_k}}\\right) V$$\n\n- $Q = X W_Q$：Query，「我在找什么」\n- $K = X W_K$：Key，「我有什么」\n- $V = X W_V$：Value，「我的内容」\n- $\\sqrt{d_k}$：缩放因子，防止点积过大\n\n### 直觉理解\n\nSelf-Attention 让序列中的每个位置都可以「看到」所有其他位置，并根据相关性加权聚合信息。这解决了 RNN 的长距离依赖问题。"),
    md_cell("## 2. 手算验证\n\n### 单头注意力计算\n\n设 $d_k = 2$，序列长度 $N = 2$：\n\n$$Q = \\begin{bmatrix} 1 & 0 \\\\ 0 & 1 \\end{bmatrix}, \\quad K = \\begin{bmatrix} 1 & 1 \\\\ 0 & 1 \\end{bmatrix}, \\quad V = \\begin{bmatrix} 1 \\\\ 2 \\end{bmatrix}\n\n$$\n\n1. $QK^T = \\begin{bmatrix} 2 & 1 \\\\ 1 & 1 \\end{bmatrix}$\n\n2. $\\frac{QK^T}{\\sqrt{2}} = \\begin{bmatrix} 1.41 & 0.71 \\\\ 0.71 & 0.71 \\end{bmatrix}$\n\n3. softmax 行归一化：\n   - 第一行：$\\text{softmax}([1.41, 0.71]) \\approx [0.67, 0.33]$\n   - 第二行：$\\text{softmax}([0.71, 0.71]) = [0.50, 0.50]$\n\n4. 输出 $= A \\cdot V$\n   - 第一个位置：$0.67 \\times 1 + 0.33 \\times 2 = 1.33$\n   - 第二个位置：$0.50 \\times 1 + 0.50 \\times 2 = 1.50$"),
    code_cell("# 从零实现 Self-Attention\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib\nmatplotlib.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']\nmatplotlib.rcParams['axes.unicode_minus'] = False\nnp.random.seed(42)\n\ndef softmax(x, axis=-1):\n    x = x - np.max(x, axis=axis, keepdims=True)\n    exp_x = np.exp(x)\n    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)\n\ndef self_attention(Q, K, V, mask=None):\n    \"\"\"缩放点积注意力\n    Q, K, V: (N, d)\n    返回: (N, d_v), attention_weights (N, N)\n    \"\"\"\n    d_k = K.shape[-1]\n    scores = Q @ K.T / np.sqrt(d_k)  # (N, N)\n    if mask is not None:\n        scores = np.where(mask == 0, -1e9, scores)\n    attention = softmax(scores, axis=-1)  # (N, N)\n    out = attention @ V  # (N, d_v)\n    return out, attention\n\n# 验证手算结果\nQ = np.array([[1, 0], [0, 1]], dtype=float)\nK = np.array([[1, 1], [0, 1]], dtype=float)\nV = np.array([[1], [2]], dtype=float)\nout, attn = self_attention(Q, K, V)\nprint(f\"注意力权重:\\n{attn}\")\nprint(f\"输出: {out.flatten()}\")\nprint(f\"期望输出: [1.33, 1.50]\")"),
    code_cell("# 从零实现 Multi-Head Attention\ndef multi_head_attention(X, W_Q, W_K, W_V, W_O, num_heads=4):\n    \"\"\"多头注意力\n    X: (N, d_model)\n    W_Q, W_K, W_V: (d_model, d_model)\n    W_O: (d_model, d_model)\n    \"\"\"\n    N, d_model = X.shape\n    d_k = d_model // num_heads\n    \n    Q = X @ W_Q  # (N, d_model)\n    K = X @ W_K\n    V = X @ W_V\n    \n    # 分割为多头\n    Q = Q.reshape(N, num_heads, d_k).transpose(1, 0, 2)  # (h, N, d_k)\n    K = K.reshape(N, num_heads, d_k).transpose(1, 0, 2)\n    V = V.reshape(N, num_heads, d_k).transpose(1, 0, 2)\n    \n    # 每头注意力\n    outputs = []\n    attentions = []\n    for h in range(num_heads):\n        out_h, attn_h = self_attention(Q[h], K[h], V[h])\n        outputs.append(out_h)\n        attentions.append(attn_h)\n    \n    # 拼接 + 线性变换\n    concat = np.concatenate(outputs, axis=-1)  # (N, d_model)\n    out = concat @ W_O\n    return out, attentions\n\n# 测试\nd_model = 64\nN = 10\nX = np.random.randn(N, d_model)\nW_Q = np.random.randn(d_model, d_model) * 0.1\nW_K = np.random.randn(d_model, d_model) * 0.1\nW_V = np.random.randn(d_model, d_model) * 0.1\nW_O = np.random.randn(d_model, d_model) * 0.1\n\nout, attentions = multi_head_attention(X, W_Q, W_K, W_V, W_O, num_heads=4)\nprint(f\"输入形状: {X.shape}\")\nprint(f\"输出形状: {out.shape}\")\nprint(f\"注意力头数: 4, 每头维度: {d_model // 4}\")"),
    code_cell("# 可视化注意力权重\nfig, axes = plt.subplots(1, 4, figsize=(20, 5))\nfor h in range(4):\n    im = axes[h].imshow(attentions[h], cmap='Oranges', aspect='auto')\n    axes[h].set_title(f'Head {h+1}')\n    axes[h].set_xlabel('Key Position')\n    axes[h].set_ylabel('Query Position')\n    plt.colorbar(im, ax=axes[h], fraction=0.046)\nplt.suptitle('Multi-Head Attention 权重可视化', fontsize=14)\nplt.tight_layout()\nplt.savefig('lecture-08-transformers/attention_weights.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 3. ViT: Vision Transformer\n\n### Patch Embedding\n\nViT 将图像分割为固定大小的 patch，每个 patch 展平后线性投影为向量：\n\n$$\\mathbf{z}_i = \\text{Linear}(\\text{flatten}(\\text{patch}_i)) + \\text{PE}_i$$\n\n然后送入标准 Transformer Encoder。\n\n[[Dosovitskiy et al., 2020]](https://arxiv.org/abs/2010.11929) ViT 论文\n\n### CNN vs ViT 对比\n\n| 特性 | CNN | ViT |\n|------|-----|------|\n| **归纳偏置** | 局部性、平移等变 | 无（全局注意力） |\n| **数据效率** | 小数据即可 | 需要大数据预训练 |\n| **计算量** | O(HW) | O(N²), N=patch数 |\n| **感受野** | 随深度增长 | 第一层就是全局 |\n\nViT 放弃了 CNN 的归纳偏置，用更多数据学习——这就是「An Image is Worth 16×16 Words」。"),
    md_cell("## 作业\n\n### 作业 1：实现 Positional Encoding\n\n完成 ViT 中使用的正弦位置编码："),
    code_cell("# 作业 1：实现 Positional Encoding\ndef positional_encoding(seq_len, d_model):\n    \"\"\"正弦位置编码\n    PE[pos, 2i] = sin(pos / 10000^(2i/d_model))\n    PE[pos, 2i+1] = cos(pos / 10000^(2i/d_model))\n    \"\"\"\n    pe = np.zeros((seq_len, d_model))\n    position = np.arange(seq_len)[:, None]\n    # 在此实现\n    pass\n    return pe\n\npe = positional_encoding(10, 8)\nassert pe.shape == (10, 8)\nassert np.allclose(pe[0, 0], 0.0)  # sin(0) = 0\nassert np.allclose(pe[0, 1], 1.0)  # cos(0) = 1\nprint(\"作业 1 通过!\")"),
    md_cell("## 参考文献\n\n1. **Attention is All You Need** - Vaswani et al., 2017. [arXiv:1706.03762](https://arxiv.org/abs/1706.03762)\n2. **An Image is Worth 16×16 Words (ViT)** - Dosovitskiy et al., 2020. [arXiv:2010.11929](https://arxiv.org/abs/2010.11929)\n3. **The Illustrated Transformer** - Jay Alammar. [jalammar.github.io](http://jalammar.github.io/illustrated-transformer/)\n4. **Attention? Attention!** - Lilian Weng. [lilianweng.github.io](https://lilianweng.github.io/posts/2018-06-24-attention/)\n\n---\n\n> 本节内容参考 [Stanford CS231n Lecture 8](https://cs231n.stanford.edu/)"),
])

# ============================================================
# Lecture 09: Object Detection & Segmentation
# ============================================================
nb09 = make_notebook([
    md_cell("# 目标检测与图像分割\n\n> **斯坦福 CS231n Lecture 9** | Object Detection, Image Segmentation, Visualizing\n\n## 本章导读\n\n从图像分类到目标检测和像素级分割——本节介绍视觉理解的核心任务。从 R-CNN 到 YOLO 到 DETR，理解检测架构的演进。\n\n**学习目标：**\n- 理解目标检测的两阶段 vs 一阶段方法\n- 掌握 IoU 和 NMS 的原理与实现\n- 了解语义分割、实例分割、全景分割的区别\n\n**参考来源：** [CS231n Detection](https://cs231n.github.io/) | [YOLO](https://arxiv.org/abs/1506.02640) | [DETR](https://arxiv.org/abs/2005.12872)"),
    md_cell("## 1. 任务定义\n\n### 图像分类 → 目标检测 → 实例分割\n\n| 任务 | 输出 | 复杂度 |\n|------|------|--------|\n| **分类** | 类别标签 | O(1) |\n| **检测** | 边界框 + 类别 | O(N) |\n| **语义分割** | 每像素类别 | O(H×W) |\n| **实例分割** | 每像素实例掩码 | O(H×W×N) |\n| **全景分割** | 语义 + 实例 | O(H×W×N) |"),
    md_cell("## 2. IoU (Intersection over Union)\n\n### 手算 IoU\n\n框 A: $[0, 0, 4, 4]$（$[x_1, y_1, x_2, y_2]$）\n框 B: $[2, 2, 6, 6]$\n\n- 交集: $[\\max(0,2), \\max(0,2), \\min(4,6), \\min(4,6)] = [2, 2, 4, 4]$\n- 交集面积: $(4-2) \\times (4-2) = 4$\n- A 面积: $4 \\times 4 = 16$\n- B 面积: $4 \\times 4 = 16$\n- 并集: $16 + 16 - 4 = 28$\n- IoU: $4 / 28 \\approx 0.143$"),
    code_cell("# 从零实现 IoU 和 NMS\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib\nmatplotlib.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']\nmatplotlib.rcParams['axes.unicode_minus'] = False\nnp.random.seed(42)\n\ndef compute_iou(boxA, boxB):\n    \"\"\"计算两个边界框的 IoU\n    box: [x1, y1, x2, y2]\n    \"\"\"\n    x1 = max(boxA[0], boxB[0])\n    y1 = max(boxA[1], boxB[1])\n    x2 = min(boxA[2], boxB[2])\n    y2 = min(boxA[3], boxB[3])\n    inter_w = max(0, x2 - x1)\n    inter_h = max(0, y2 - y1)\n    inter_area = inter_w * inter_h\n    areaA = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])\n    areaB = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])\n    union = areaA + areaB - inter_area\n    return inter_area / union if union > 0 else 0\n\n# 验证手算\nboxA = [0, 0, 4, 4]\nboxB = [2, 2, 6, 6]\niou = compute_iou(boxA, boxB)\nprint(f\"IoU = {iou:.4f}  (期望: 0.1429)\")\nassert abs(iou - 4/28) < 1e-4\n\ndef nms(boxes, scores, iou_threshold=0.5):\n    \"\"\"非极大值抑制\"\"\"\n    indices = np.argsort(scores)[::-1]\n    keep = []\n    while len(indices) > 0:\n        i = indices[0]\n        keep.append(i)\n        rest = indices[1:]\n        indices = [j for j in rest if compute_iou(boxes[i], boxes[j]) < iou_threshold]\n    return keep\n\n# 测试 NMS\nboxes = [[0, 0, 10, 10], [1, 1, 11, 11], [20, 20, 30, 30]]\nscores = [0.9, 0.8, 0.7]\nkeep = nms(boxes, scores, iou_threshold=0.3)\nprint(f\"NMS 保留: {keep} (期望: [0, 2])\"),"),
    code_cell("# 可视化 IoU 和 NMS\nfig, axes = plt.subplots(1, 2, figsize=(14, 5))\n\n# IoU 可视化\nax = axes[0]\nrectA = plt.Rectangle((0, 0), 4, 4, linewidth=2, edgecolor='#ea580c', facecolor='#fed7aa', label='Box A')\nrectB = plt.Rectangle((2, 2), 4, 4, linewidth=2, edgecolor='#2563eb', facecolor='#bfdbfe', label='Box B')\nax.add_patch(rectA)\nax.add_patch(rectB)\nax.set_xlim(-1, 8)\nax.set_ylim(-1, 8)\nax.set_aspect('equal')\nax.set_title(f'IoU = {iou:.4f}')\nax.legend()\n\n# NMS 可视化\nax = axes[1]\ncolors = ['#ea580c', '#dc2626', '#16a34a']\nlabels = ['score=0.9 (keep)', 'score=0.8 (suppress)', 'score=0.7 (keep)']\nfor i, (box, score, c, l) in enumerate(zip(boxes, scores, colors, labels)):\n    x1, y1, x2, y2 = box\n    rect = plt.Rectangle((x1, y1), x2-x1, y2-y1, linewidth=2, edgecolor=c, facecolor='none', label=l)\n    ax.add_patch(rect)\n    ax.text(x1, y1-1, f'{score}', color=c, fontsize=10)\nax.set_xlim(-5, 35)\nax.set_ylim(-5, 35)\nax.set_aspect('equal')\nax.set_title('NMS 结果')\nax.legend(loc='upper right')\n\nplt.tight_layout()\nplt.savefig('lecture-09-detection/iou_nms.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 3. 检测架构演进\n\n### 两阶段检测器\n1. **R-CNN** (2014): Selective Search → CNN → SVM\n2. **Fast R-CNN** (2015): RoI Pooling + 端到端\n3. **Faster R-CNN** (2015): RPN + 端到端\n\n### 一阶段检测器\n1. **YOLO** (2015): 单次前向，实时检测\n2. **SSD** (2016): 多尺度特征图\n3. **RetinaNet** (2017): Focal Loss\n\n### DETR (2020): Transformer 检测器\n- 取代 NMS 和 Anchor，用二分图匹配\n- 端到端训练，架构简洁\n\n[[Ren et al., 2015]](https://arxiv.org/abs/1506.01497) Faster R-CNN\n[[Redmon et al., 2015]](https://arxiv.org/abs/1506.02640) YOLO\n[[Carion et al., 2020]](https://arxiv.org/abs/2005.12872) DETR"),
    code_cell("# 模拟 YOLO 检测过程\n# 将图像分为 SxS 网格，每个网格预测 B 个框\ndef yolo_grid_visualization(S=7, B=2):\n    \"\"\"可视化 YOLO 网格\"\"\"\n    fig, ax = plt.subplots(figsize=(8, 8))\n    # 图像区域\n    ax.set_xlim(0, 1)\n    ax.set_ylim(0, 1)\n    ax.set_aspect('equal')\n    \n    # 网格线\n    for i in range(S + 1):\n        ax.axhline(y=i/S, color='gray', linewidth=0.5, alpha=0.5)\n        ax.axvline(x=i/S, color='gray', linewidth=0.5, alpha=0.5)\n    \n    # 模拟检测到的物体\n    objects = [\n        {'center': (0.3, 0.7), 'size': (0.15, 0.25), 'label': '猫', 'conf': 0.92},\n        {'center': (0.7, 0.3), 'size': (0.20, 0.15), 'label': '狗', 'conf': 0.85},\n    ]\n    \n    for obj in objects:\n        cx, cy = obj['center']\n        w, h = obj['size']\n        rect = plt.Rectangle((cx-w/2, cy-h/2), w, h, linewidth=2, edgecolor='#ea580c', facecolor='#fed7aa50')\n        ax.add_patch(rect)\n        ax.text(cx, cy, f\"{obj['label']}\\n{obj['conf']:.2f}\", ha='center', va='center', fontsize=9)\n    \n    ax.set_title(f'YOLO 检测可视化 (S={S}, B={B})')\n    ax.set_xlabel('x')\n    ax.set_ylabel('y')\n    plt.tight_layout()\n    plt.savefig('lecture-09-detection/yolo_grid.png', dpi=150, bbox_inches='tight')\n    plt.show()\n\nyolo_grid_visualization()"),
    md_cell("## 作业\n\n### 作业 1：实现 mAP 计算\n\nmAP (mean Average Precision) 是检测任务的标准评价指标。"),
    code_cell("# 作业 1：实现 AP 计算\ndef average_precision(predictions, ground_truths, iou_threshold=0.5):\n    \"\"\"计算单类别的 Average Precision\n    predictions: list of (box, score)\n    ground_truths: list of box\n    \"\"\"\n    # 按置信度排序\n    predictions.sort(key=lambda x: -x[1])\n    tp = np.zeros(len(predictions))\n    fp = np.zeros(len(predictions))\n    gt_matched = [False] * len(ground_truths)\n    \n    for i, (pred_box, _) in enumerate(predictions):\n        best_iou = 0\n        best_gt = -1\n        for j, gt_box in enumerate(ground_truths):\n            iou = compute_iou(pred_box, gt_box)\n            if iou > best_iou:\n                best_iou = iou\n                best_gt = j\n        \n        if best_iou >= iou_threshold and not gt_matched[best_gt]:\n            tp[i] = 1\n            gt_matched[best_gt] = True\n        else:\n            fp[i] = 1\n    \n    tp_cum = np.cumsum(tp)\n    fp_cum = np.cumsum(fp)\n    precision = tp_cum / (tp_cum + fp_cum + 1e-8)\n    recall = tp_cum / (len(ground_truths) + 1e-8)\n    \n    # 使用梯形法则计算 AP\n    ap = 0\n    for i in range(1, len(precision)):\n        ap += (recall[i] - recall[i-1]) * precision[i]\n    return ap\n\n# 测试\npreds = [([0, 0, 10, 10], 0.9), ([20, 20, 30, 30], 0.8)]\ngts = [[0, 0, 10, 10], [20, 20, 30, 30]]\nap = average_precision(preds, gts)\nprint(f\"AP = {ap:.4f}\")\nassert ap > 0.9, \"完美检测应有高AP\"\nprint(\"作业 1 通过!\")"),
    md_cell("## 参考文献\n\n1. **R-CNN** - Girshick et al., 2014. [arXiv:1311.2524](https://arxiv.org/abs/1311.2524)\n2. **Fast R-CNN** - Girshick, 2015. [arXiv:1504.08083](https://arxiv.org/abs/1504.08083)\n3. **Faster R-CNN** - Ren et al., 2015. [arXiv:1506.01497](https://arxiv.org/abs/1506.01497)\n4. **YOLO** - Redmon et al., 2015. [arXiv:1506.02640](https://arxiv.org/abs/1506.02640)\n5. **DETR** - Carion et al., 2020. [arXiv:2005.12872](https://arxiv.org/abs/2005.12872)\n6. **FCN** - Long et al., 2015. [arXiv:1411.4038](https://arxiv.org/abs/1411.4038)\n\n---\n\n> 本节内容参考 [Stanford CS231n Lecture 9](https://cs231n.stanford.edu/)"),
])

# ============================================================
# Lecture 12: Self-Supervised Learning
# ============================================================
nb12 = make_notebook([
    md_cell("# 自监督学习\n\n> **斯坦福 CS231n Lecture 12** | Self-supervised Learning\n\n## 本章导读\n\n自监督学习是视觉预训练的新范式——无需人工标注，从数据本身学习表示。本节从对比学习到 DINO/CLIP，理解自监督如何接近甚至超越有监督方法。\n\n**学习目标：**\n- 理解自监督学习的动机和 pretext task\n- 掌握对比学习（InfoNCE）原理\n- 了解 DINO 和 CLIP 的核心思想\n- 从零实现简单的对比学习框架\n\n**参考来源：** [Self-supervised Learning Blog](https://lilianweng.github.io/lil-log/2019/11/10/self-supervised-learning.html) | [DINO](https://arxiv.org/abs/2104.14294)"),
    md_cell("## 1. 为什么需要自监督学习？\n\n### 有监督学习的局限\n- **标注成本高**：ImageNet 标注耗时多年\n- **长尾问题**：罕见类别标注不足\n- **通用性差**：每个任务需专门标注\n\n### 自监督学习核心思想\n从数据本身构造监督信号：\n- **Pretext Task**: 旋转预测、拼图、遮罩预测\n- **Contrastive Learning**: 正样本拉近，负样本推远\n- **Non-Contrastive**: DINO、BYOL，无需负样本\n\n### 发展脉络\n```\nPretext Task (2015-2018) → Contrastive (2019-2020) → Non-Contrastive (2021+)\nMoCo, SimCLR, BYOL, DINO, MAE\n```"),
    md_cell("## 2. 对比学习：InfoNCE 损失\n\n### 公式\n\n$$\\mathcal{L} = -\\log \\frac{\\exp(\\text{sim}(z_i, z_i^+) / \\tau)}{\\sum_{j} \\exp(\\text{sim}(z_i, z_j) / \\tau)}$$\n\n其中：\n- $z_i$：查询样本的特征\n- $z_i^+$：正样本（同一图像的不同增强）\n- $z_j$：所有样本（含正样本和负样本）\n- $\\tau$：温度参数\n\n### 手算验证\n\n设 3 个样本，$\\tau=1$，相似度 $[s_+, s_-, s_-] = [0.8, 0.2, 0.1]$。\n\n- $\\exp(0.8) = 2.23$, $\\exp(0.2) = 1.22$, $\\exp(0.1) = 1.11$\n- 分母 $= 2.23 + 1.22 + 1.11 = 4.56$\n- 损失 $= -\\log(2.23 / 4.56) = -\\log(0.489) = 0.715$"),
    code_cell("# 从零实现对比学习损失\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib\nmatplotlib.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']\nmatplotlib.rcParams['axes.unicode_minus'] = False\nnp.random.seed(42)\n\ndef info_nce_loss(z_query, z_positive, z_negatives, tau=0.1):\n    \"\"\"InfoNCE 损失\n    z_query: (D,)\n    z_positive: (D,)\n    z_negatives: (N, D)\n    \"\"\"\n    pos_sim = np.dot(z_query, z_positive) / (np.linalg.norm(z_query) * np.linalg.norm(z_positive))\n    neg_sims = np.array([np.dot(z_query, zn) / (np.linalg.norm(z_query) * np.linalg.norm(zn)) for zn in z_negatives])\n    \n    all_sims = np.concatenate([[pos_sim], neg_sims]) / tau\n    log_sum_exp = np.log(np.sum(np.exp(all_sims)))\n    loss = -pos_sim / tau + log_sum_exp\n    return loss\n\n# 验证手算\nz_q = np.array([1, 0])\nz_p = np.array([0.8, 0.6])  # 相似度约0.8\nz_n1 = np.array([0.2, 0.98])  # 相似度约0.2\nz_n2 = np.array([0.1, 0.995])  # 相似度约0.1\nloss = info_nce_loss(z_q, z_p, np.array([z_n1, z_n2]), tau=1.0)\nprint(f\"InfoNCE 损失: {loss:.4f} (期望: ~0.715)\")"),
    code_cell("# 模拟对比学习训练过程\n# 生成特征空间：3个类别，每类有锚点和正样本\nclasses = ['猫', '狗', '鸟']\nanchors = np.array([[1, 0], [0, 1], [0.5, 0.5]])\n\n# 训练过程：正样本拉近、负样本推远\nfig, axes = plt.subplots(1, 2, figsize=(14, 6))\n\n# 训练前（随机特征）\nnp.random.seed(42)\nbefore = np.random.randn(30, 2) * 2\nlabels = np.repeat([0, 1, 2], 10)\ncolors = ['#ea580c', '#2563eb', '#16a34a']\nfor c in range(3):\n    axes[0].scatter(before[labels==c, 0], before[labels==c, 1], c=colors[c], label=classes[c], alpha=0.6, s=50)\naxes[0].set_title('训练前（随机特征）')\naxes[0].legend()\naxes[0].set_xlim(-6, 6)\naxes[0].set_ylim(-6, 6)\n\n# 训练后（聚类）\nfor c in range(3):\n    cluster = np.random.randn(10, 2) * 0.5 + anchors[c]\n    axes[1].scatter(cluster[:, 0], cluster[:, 1], c=colors[c], label=classes[c], alpha=0.6, s=50)\naxes[1].set_title('训练后（对比学习）')\naxes[1].legend()\naxes[1].set_xlim(-6, 6)\naxes[1].set_ylim(-6, 6)\n\nplt.suptitle('对比学习：特征空间变化', fontsize=14)\nplt.tight_layout()\nplt.savefig('lecture-12-ssl/contrastive_learning.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 3. DINO 与 CLIP\n\n### DINO (Self-Distillation)\n\nDINO 使用师生网络，无需负样本：\n- 学生网络学习匹配教师网络的输出分布\n- 教师网络用 EMA 更新\n- 用 Centering + Sharpening 防止坍缩\n\n[[Caron et al., 2021]](https://arxiv.org/abs/2104.14294) DINO 论文\n\n### CLIP (Contrastive Language-Image Pre-training)\n\nCLIP 联合训练图像编码器和文本编码器：\n- 图文对 $(I_i, T_i)$ 为正样本\n- 不同图文对为负样本\n- 学习对齐的图文特征空间\n\n[[Radford et al., 2021]](https://arxiv.org/abs/2103.00020) CLIP 论文\n\n### 比较\n\n| 方法 | 监督信号 | 需负样本 | 核心创新 |\n|------|---------|---------|---------|\n| SimCLR | 对比 | 是 | 大 batch + 强增强 |\n| BYOL | 预测 | 否 | Predictor + EMA |\n| DINO | 自蒸馏 | 否 | Centering + Sharpening |\n| CLIP | 图文对比 | 是 | 跨模态对齐 |\n| MAE | 重建 | 否 | 高比例遮罩重建 |"),
    md_cell("## 作业\n\n### 作业 1：实现 SimCLR 数据增强\n\nSimCLR 的成功关键在于强数据增强。实现以下增强组合："),
    code_cell("# 作业 1：实现 SimCLR 增强管道\ndef simclr_augment(image):\n    \"\"\"SimCLR 数据增强\n    1. 随机裁剪 + 调整大小\n    2. 随机颜色抖动\n    3. 随机高斯模糊\n    \"\"\"\n    # 在此实现\n    pass\n\n# 测试\nimg = np.random.rand(32, 32, 3)\naug1 = simclr_augment(img.copy())\naug2 = simclr_augment(img.copy())\nassert aug1.shape == aug2.shape == img.shape\nprint(\"作业 1 通过!\")"),
    md_cell("## 参考文献\n\n1. **Self-Supervised Learning Blog** - Lilian Weng. [lilianweng.github.io](https://lilianweng.github.io/lil-log/2019/11/10/self-supervised-learning.html)\n2. **DINO: Emerging Properties in Self-Supervised ViTs** - Caron et al., 2021. [arXiv:2104.14294](https://arxiv.org/abs/2104.14294)\n3. **CLIP: Learning Transferable Visual Models** - Radford et al., 2021. [arXiv:2103.00020](https://arxiv.org/abs/2103.00020)\n4. **SimCLR: A Simple Framework for Contrastive Learning** - Chen et al., 2020. [arXiv:2002.05709](https://arxiv.org/abs/2002.05709)\n5. **MAE: Masked Autoencoders** - He et al., 2021. [arXiv:2111.06377](https://arxiv.org/abs/2111.06377)\n\n---\n\n> 本节内容参考 [Stanford CS231n Lecture 12](https://cs231n.stanford.edu/)"),
])

# ============================================================
# Lecture 13: Generative Models
# ============================================================
nb13 = make_notebook([
    md_cell("# 生成模型\n\n> **斯坦福 CS231n Lecture 13** | Generative Models 1\n\n## 本章导读\n\n生成模型学习数据分布并生成新样本。本节从 VAE 到 GAN 到扩散模型，理解三种生成范式的原理和差异。\n\n**学习目标：**\n- 理解 VAE 的编码-解码框架和 ELBO\n- 掌握 GAN 的对抗训练原理\n- 了解扩散模型的前向加噪和反向去噪\n- 从零实现简单的 VAE 和 GAN\n\n**参考来源：** [ELBO What & Why](https://yunfanj.com/blog/2021/01/11/ELBO.html)"),
    md_cell("## 1. 三种生成模型\n\n| 类型 | 代表 | 训练方式 | 优势 | 劣势 |\n|------|------|---------|------|------|\n| **VAE** | VAE | 变分推断 | 稳定、有编码器 | 模糊 |\n| **GAN** | GAN, StyleGAN | 对抗训练 | 清晰、逼真 | 不稳定、模式坍缩 |\n| **Diffusion** | DDPM | 去噪得分匹配 | 质量最高、多样 | 速度慢 |\n\n### 统一视角\n所有生成模型都在学习数据分布 $p(x)$：\n- VAE：变分下界 $\\log p(x) \\geq \\text{ELBO}$\n- GAN：对抗损失（隐式估计分布）\n- Diffusion：逐步去噪 $p(x_{t-1} | x_t)$"),
    md_cell("## 2. VAE: 变分自编码器\n\n### 数学推导\n\nELBO 目标：\n$$\\mathcal{L} = \\mathbb{E}_{q(z|x)}[\\log p(x|z)] - D_{KL}(q(z|x) \\| p(z))$$\n- 第一项：重构损失\n- 第二项：KL 散度（正则化）\n\n### 重参数化技巧\n\n$$z = \\mu + \\sigma \\cdot \\epsilon, \\quad \\epsilon \\sim \\mathcal{N}(0, I)$$\n\n使得随机采样可微分，允许反向传播。\n\n### 手算 KL 散度\n\n$q(z|x) = \\mathcal{N}(\\mu, \\sigma^2)$, $p(z) = \\mathcal{N}(0, 1)$\n\n$$D_{KL} = \\frac{1}{2}(\\mu^2 + \\sigma^2 - \\log \\sigma^2 - 1)$$\n\n设 $\\mu=1, \\sigma=2$:\n$$D_{KL} = \\frac{1}{2}(1 + 4 - \\log 4 - 1) = \\frac{1}{2}(4 - 1.386) = 1.307$$"),
    code_cell("# 从零实现 VAE\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib\nmatplotlib.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']\nmatplotlib.rcParams['axes.unicode_minus'] = False\nnp.random.seed(42)\n\nclass SimpleVAE:\n    \"\"\"简化的 VAE 实现（仅 numpy）\"\"\"\n    def __init__(self, input_dim=2, latent_dim=1):\n        # 编码器参数\n        self.W_enc = np.random.randn(input_dim, latent_dim) * 0.1\n        self.b_enc_mu = np.zeros(latent_dim)\n        self.b_enc_logvar = np.zeros(latent_dim)\n        # 解码器参数\n        self.W_dec = np.random.randn(latent_dim, input_dim) * 0.1\n        self.b_dec = np.zeros(input_dim)\n    \n    def encode(self, x):\n        mu = x @ self.W_enc + self.b_enc_mu\n        logvar = x @ self.W_enc + self.b_enc_logvar\n        return mu, logvar\n    \n    def reparameterize(self, mu, logvar):\n        std = np.exp(0.5 * logvar)\n        eps = np.random.randn(*mu.shape)\n        return mu + std * eps\n    \n    def decode(self, z):\n        return z @ self.W_dec + self.b_dec\n    \n    def loss(self, x):\n        mu, logvar = self.encode(x)\n        z = self.reparameterize(mu, logvar)\n        x_recon = self.decode(z)\n        # 重构损失 (MSE)\n        recon_loss = np.mean((x - x_recon) ** 2)\n        # KL 散度\n        kl_loss = -0.5 * np.mean(1 + logvar - mu**2 - np.exp(logvar))\n        return recon_loss + kl_loss, recon_loss, kl_loss\n\n# 验证 KL 手算\nmu = np.array([[1.0]])\nlogvar = np.array([[np.log(4)]])  # sigma^2=4\nkl = -0.5 * np.mean(1 + logvar - mu**2 - np.exp(logvar))\nprint(f\"KL 散度: {kl:.4f} (期望: 1.307)\")"),
    code_cell("# VAE 训练：学习 2D 高斯分布\n# 生成训练数据\ndata = np.random.randn(500, 2) * np.array([2, 0.5])\ndata[:, 1] += np.sin(data[:, 0] * 2) * 0.5\n\nvae = SimpleVAE(input_dim=2, latent_dim=1)\nlosses, recon_losses, kl_losses = [], [], []\nlr = 0.01\nfor epoch in range(500):\n    loss, rl, kl = vae.loss(data)\n    losses.append(loss)\n    recon_losses.append(rl)\n    kl_losses.append(kl)\n    # 简单梯度下降（数值梯度）\n    eps = 1e-5\n    for param in [vae.W_enc, vae.b_enc_mu, vae.b_enc_logvar, vae.W_dec, vae.b_dec]:\n        grad = np.zeros_like(param)\n        it = np.nditer(param, flags=['multi_index'])\n        while not it.finished:\n            idx = it.multi_index\n            old = param[idx]\n            param[idx] = old + eps\n            loss_p, _, _ = vae.loss(data)\n            param[idx] = old - eps\n            loss_m, _, _ = vae.loss(data)\n            param[idx] = old\n            grad[idx] = (loss_p - loss_m) / (2 * eps)\n            it.iternext()\n        param -= lr * grad\n\n# 可视化\nfig, axes = plt.subplots(1, 3, figsize=(15, 4))\naxes[0].scatter(data[:, 0], data[:, 1], s=5, alpha=0.5, color='#2563eb')\naxes[0].set_title('训练数据')\naxes[1].plot(losses, label='Total', color='#ea580c')\naxes[1].plot(recon_losses, label='Recon', color='#2563eb')\naxes[1].plot(kl_losses, label='KL', color='#16a34a')\naxes[1].set_title('VAE 损失')\naxes[1].legend()\n# 生成新样本\nz_samples = np.random.randn(200, 1)\ngenerated = vae.decode(z_samples)\naxes[2].scatter(generated[:, 0], generated[:, 1], s=5, alpha=0.5, color='#ea580c')\naxes[2].set_title('VAE 生成')\nplt.tight_layout()\nplt.savefig('lecture-13-generative/vae_results.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 3. GAN: 生成对抗网络\n\n### 对抗损失\n\n$$\\min_G \\max_D \\mathbb{E}_{x \\sim p_{data}}[\\log D(x)] + \\mathbb{E}_{z \\sim p_z}[\\log(1 - D(G(z)))]$$\n\n- **生成器 G**：试图生成逼真样本骗过判别器\n- **判别器 D**：试图区分真实样本和生成样本\n\n### 扩散模型（Diffusion）\n\n前向过程：逐步加噪\n$$x_t = \\sqrt{\\alpha_t} x_{t-1} + \\sqrt{1 - \\alpha_t} \\epsilon, \\quad \\epsilon \\sim \\mathcal{N}(0, I)$$\n\n反向过程：学习去噪\n$$p(x_{t-1} | x_t) = \\mathcal{N}(\\mu_\\theta(x_t, t), \\sigma_t^2 I)$$\n\n扩散模型目前是图像生成的主流方法（DALL-E 3, Stable Diffusion 等）。"),
    code_cell("# 模拟扩散过程：前向加噪\nfrom scipy import ndimage\n\n# 生成一个简单图像\nimage = np.zeros((32, 32))\nimage[8:24, 8:24] = 1.0\nimage = ndimage.gaussian_filter(image, sigma=1)\n\n# 前向扩散\ndef forward_diffusion(x0, num_steps=10, beta_start=0.01, beta_end=0.5):\n    betas = np.linspace(beta_start, beta_end, num_steps)\n    images = [x0.copy()]\n    x = x0.copy()\n    for beta in betas:\n        x = np.sqrt(1 - beta) * x + np.sqrt(beta) * np.random.randn(*x.shape)\n        images.append(x.copy())\n    return images\n\ndiffused = forward_diffusion(image, num_steps=20)\n\n# 可视化\nfig, axes = plt.subplots(1, 6, figsize=(18, 3))\nsteps = [0, 4, 8, 12, 16, 20]\nfor ax, s in zip(axes, steps):\n    ax.imshow(diffused[s], cmap='gray', vmin=-3, vmax=3)\n    ax.set_title(f't={s}')\n    ax.axis('off')\nplt.suptitle('前向扩散过程', fontsize=14)\nplt.tight_layout()\nplt.savefig('lecture-13-generative/diffusion_forward.png', dpi=150, bbox_inches='tight')\nplt.show()"),
    md_cell("## 作业\n\n### 作业 1：计算 VAE 的 KL 散度\n\n给定 $\\mu=0.5, \\sigma=1.5$，计算 KL 散度 $D_{KL}(q(z|x) \\| p(z))$。"),
    code_cell("# 作业 1：计算 KL 散度\ndef kl_divergence_gaussian(mu, sigma):\n    \"\"\"计算 q=N(mu, sigma^2) 与 p=N(0,1) 的 KL 散度\"\"\"\n    # 在此实现\n    pass\n\nkl = kl_divergence_gaussian(0.5, 1.5)\nassert abs(kl - 0.363) < 0.01, f\"期望 0.363, 得到 {kl}\"\nprint(f\"KL 散度 = {kl:.4f}\")\nprint(\"作业 1 通过!\")"),
    md_cell("## 参考文献\n\n1. **Auto-Encoding Variational Bayes (VAE)** - Kingma & Welling, 2013. [arXiv:1312.6114](https://arxiv.org/abs/1312.6114)\n2. **Generative Adversarial Networks (GAN)** - Goodfellow et al., 2014. [arXiv:1406.2661](https://arxiv.org/abs/1406.2661)\n3. **Denoising Diffusion Probabilistic Models (DDPM)** - Ho et al., 2020. [arXiv:2006.11239](https://arxiv.org/abs/2006.11239)\n4. **ELBO What & Why** - [yunfanj.com](https://yunfanj.com/blog/2021/01/11/ELBO.html)\n5. **Understanding Diffusion Models** - Luo, 2022. [arXiv:2208.11970](https://arxiv.org/abs/2208.11970)\n\n---\n\n> 本节内容参考 [Stanford CS231n Lecture 13](https://cs231n.stanford.edu/)"),
])

# Save all notebooks
notebooks = {
    "part1-deep-learning-basics/lecture-01-intro/practice.ipynb": nb01,
    "part1-deep-learning-basics/lecture-02-classification/practice.ipynb": nb02,
    "part1-deep-learning-basics/lecture-03-optimization/practice.ipynb": nb03,
    "part1-deep-learning-basics/lecture-04-backprop/practice.ipynb": nb04,
    "part2-cnn-vision/lecture-05-cnn/practice.ipynb": nb05,
    "part2-cnn-vision/lecture-06-architectures/practice.ipynb": nb06,
    "part2-cnn-vision/lecture-08-transformers/practice.ipynb": nb08,
    "part2-cnn-vision/lecture-09-detection/practice.ipynb": nb09,
    "part3-frontiers/lecture-12-ssl/practice.ipynb": nb12,
    "part3-frontiers/lecture-13-generative/practice.ipynb": nb13,
}

for rel_path, nb in notebooks.items():
    full_path = os.path.join(BASE, rel_path)
    save_notebook(nb, full_path)
    print(f"Generated: {rel_path}")

print(f"\nTotal: {len(notebooks)} notebooks generated.")
